2025-10-23 19:53:40,470 INFO    MainThread:11960 [wandb_setup.py:_flush():81] Current SDK version is 0.22.2
2025-10-23 19:53:40,470 INFO    MainThread:11960 [wandb_setup.py:_flush():81] Configure stats pid to 11960
2025-10-23 19:53:40,470 INFO    MainThread:11960 [wandb_setup.py:_flush():81] Loading settings from C:\Users\madis\.config\wandb\settings
2025-10-23 19:53:40,470 INFO    MainThread:11960 [wandb_setup.py:_flush():81] Loading settings from C:\Users\madis\Desktop\supervisor_remote\supervisor\wandb\settings
2025-10-23 19:53:40,470 INFO    MainThread:11960 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-10-23 19:53:40,470 INFO    MainThread:11960 [wandb_init.py:setup_run_log_directory():705] Logging user logs to C:\Users\madis\Desktop\supervisor_remote\supervisor\wandb\run-20251023_195340-rj3e5y18\logs\debug.log
2025-10-23 19:53:40,470 INFO    MainThread:11960 [wandb_init.py:setup_run_log_directory():706] Logging internal logs to C:\Users\madis\Desktop\supervisor_remote\supervisor\wandb\run-20251023_195340-rj3e5y18\logs\debug-internal.log
2025-10-23 19:53:40,470 INFO    MainThread:11960 [wandb_init.py:init():832] calling init triggers
2025-10-23 19:53:40,470 INFO    MainThread:11960 [wandb_init.py:init():837] wandb.init called with sweep_config: {}
config: {'num_iterations': 1, 'num_steps': 20, 'batch_size': 2, 'num_generations': 4, 'max_completion_length': 300, 'beta': 0.01, 'learning_rate': 5e-06, 'mu': 2, 'epsilon': 0.2, '_wandb': {}}
2025-10-23 19:53:40,470 INFO    MainThread:11960 [wandb_init.py:init():880] starting backend
2025-10-23 19:53:42,736 INFO    MainThread:11960 [wandb_init.py:init():883] sending inform_init request
2025-10-23 19:53:42,745 INFO    MainThread:11960 [wandb_init.py:init():891] backend started and connected
2025-10-23 19:53:42,745 INFO    MainThread:11960 [wandb_init.py:init():961] updated telemetry
2025-10-23 19:53:42,766 INFO    MainThread:11960 [wandb_init.py:init():985] communicating run to backend with 90.0 second timeout
2025-10-23 19:53:43,112 INFO    MainThread:11960 [wandb_init.py:init():1036] starting run threads in backend
2025-10-23 19:53:43,266 INFO    MainThread:11960 [wandb_run.py:_console_start():2509] atexit reg
2025-10-23 19:53:43,266 INFO    MainThread:11960 [wandb_run.py:_redirect():2357] redirect: wrap_raw
2025-10-23 19:53:43,266 INFO    MainThread:11960 [wandb_run.py:_redirect():2426] Wrapping output streams.
2025-10-23 19:53:43,266 INFO    MainThread:11960 [wandb_run.py:_redirect():2449] Redirects installed.
2025-10-23 19:53:43,268 INFO    MainThread:11960 [wandb_init.py:init():1076] run started, returning control to user process
2025-10-23 19:53:46,525 INFO    wandb-AsyncioManager-main:11960 [service_client.py:_forward_responses():80] Reached EOF.
2025-10-23 19:53:46,525 INFO    wandb-AsyncioManager-main:11960 [mailbox.py:close():137] Closing mailbox, abandoning 1 handles.
2025-10-23 19:53:46,961 ERROR   MainThread:11960 [redirect.py:_on_write():664] [all runs] error in stdout callback
Traceback (most recent call last):
  File "C:\Users\madis\anaconda3\envs\openthought\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Users\madis\anaconda3\envs\openthought\lib\site-packages\wandb\sdk\wandb_run.py", line 2430, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "C:\Users\madis\anaconda3\envs\openthought\lib\site-packages\wandb\sdk\wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\madis\anaconda3\envs\openthought\lib\site-packages\wandb\sdk\wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\madis\anaconda3\envs\openthought\lib\site-packages\wandb\sdk\wandb_run.py", line 1595, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Users\madis\anaconda3\envs\openthought\lib\site-packages\wandb\sdk\interface\interface.py", line 802, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Users\madis\anaconda3\envs\openthought\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 37, in _publish_output_raw
    self._publish(rec)
  File "C:\Users\madis\anaconda3\envs\openthought\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 43, in _publish
    self._asyncer.run(lambda: self._client.publish(request))
  File "C:\Users\madis\anaconda3\envs\openthought\lib\site-packages\wandb\sdk\lib\asyncio_manager.py", line 136, in run
    return future.result()
  File "C:\Users\madis\anaconda3\envs\openthought\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\madis\anaconda3\envs\openthought\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\madis\anaconda3\envs\openthought\lib\site-packages\wandb\sdk\lib\asyncio_manager.py", line 219, in _wrap
    return await fn()
  File "C:\Users\madis\anaconda3\envs\openthought\lib\site-packages\wandb\sdk\lib\service\service_client.py", line 38, in publish
    await self._send_server_request(request)
  File "C:\Users\madis\anaconda3\envs\openthought\lib\site-packages\wandb\sdk\lib\service\service_client.py", line 64, in _send_server_request
    await self._writer.drain()
  File "C:\Users\madis\anaconda3\envs\openthought\lib\asyncio\streams.py", line 371, in drain
    await self._protocol._drain_helper()
  File "C:\Users\madis\anaconda3\envs\openthought\lib\asyncio\streams.py", line 167, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
